config/routes.rb
Rails.application.routes.draw do

  get 'pictures/:id/show' => 'pictures#show', as: 'picture_show_one'
  get 'picture/:id/show_user_pictures' => 'pictures#show_user_pictures', as: 'show_user_pictures'

  ActiveAdmin.routes(self)

  root 'pictures#index'

  resource :pictures

  devise_for :users

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/gallery_picture.rb
class GalleryPicture < ActiveRecord::Base
  belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :item_picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :item_picture, content_type: /\Aimage\/.*\Z/
  belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base

  has_attached_file :img_picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img_picture, content_type: /\Aimage\/.*\Z/

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_many :pictures
  has_many :gallery_pictures
has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    @pictures = Picture.order(created_at: :desc)
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def show_user_pictures
    @user = User.find(params[:id])
    @pictures = @user.pictures.order(created_at: :desc)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if @picture.save
      flash[:success] = 'Your picture has been created successfully'
      redirect_to root_url
    else
      render 'new'
    end
  end


  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update(picture_params)

      redirect_to pictures_path
    else
      render 'edit'
    end
  end

  def destroy
    Picture.destroy(params[:id])

    redirect_to pictures_path
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :img_picture )
  end

  def correct_user
    @picture = Picture.find(params[:id])
    if @picture.user != current_user       #unless @notice.user == current_user || current_user.admin?
      flash[:danger] = 'This is not your notice.'
      redirect_to root_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/gallery_pictures_helper.rb
module GalleryPicturesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Gallery', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="navbar-text"> Hello, <%= current_user.name %></li>
            <li><%= link_to 'Add picture', new_pictures_path %></li>
            <li><%= link_to 'Sign out',  destroy_user_session_path, method: :delete%></li>

        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">


  <%= yield %>

</div>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for  @picture do |f| %>


    <% if @picture.errors.any? %>
        <div class="errors">
          Total errors: <%= @picture.errors.count %>
          <ul>
            <% @picture.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :img_picture %>
      <%= f.file_field :img_picture %>
    </div>
    <br>

    <div>
      <%= f.submit %>
    </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Pictures#edit</h1>
<p>Find me in app/views/pictures/edit.html.erb</p>

app/views/pictures/index.html.erb
<h1>Images#index</h1>
<div class="row">

  <div class="col-sm-1">
  </div>


  <div class="col-md-11">
    <div class="row">
      <% @pictures.each do |picture| %>

          <div class="col-sm-4 product-item">
            <div class="panel panel-default">
              <div class="panel-body">
                <%= link_to picture.title, picture_show_one_path(picture)%>
                <td> <%= image_tag picture.img_picture.url(:medium) %></td>
                <br/>

                <button class="btn btn-default">View</button>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pictures/new.html.erb
<%= render 'form' %>

app/views/pictures/show.html.erb
<%= link_to 'List of all pictures', root_path %> > <%= @picture.title %>
<br>


 <%= image_tag @picture.img_picture.url(:medium) %>

<p>
  <% if current_user == @picture.user %>
      <%= link_to 'Edit ', edit_pictures_path, class: 'btn btn-primary' %>
      <%= link_to 'Delete ', pictures_path(@picture), method: :delete, class: 'btn btn-danger' %>
  <% end %>
</p>